/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class psl_ai2tv_client_AI2TVJNIJava */

#ifndef _Included_psl_ai2tv_client_AI2TVJNIJava
#define _Included_psl_ai2tv_client_AI2TVJNIJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     psl_ai2tv_client_AI2TVJNIJava
 * Method:    loadImage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_psl_ai2tv_client_AI2TVJNIJava_loadImage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     psl_ai2tv_client_AI2TVJNIJava
 * Method:    displayImage
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_psl_ai2tv_client_AI2TVJNIJava_displayImage
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
